### ISSUE TITLE
Can't select text in popup

### ISSUE THREAD

**Issue by inoyakaigor** [Wixel/jquery-popdown#3]
When i start select text popup is closed.

**Comment by hellocosmin** [comment]
The plugin includes some code that basically says: 'if anything except a link was clicked inside the popup, close the popup'. You can simply remove that piece of code, here it is:

    // General element to close the popdown
		$(document).on('click', '.close-popdown', function(e){
			if($(this).is('a')) {
				e.preventDefault();
			}
			$.fn.close_popdown();
		});

**Comment by kamaroly** [comment]
Had same issue, you have to go to `jquery.popdown.js` at line 114 until line 126 then comment below lines to fix this issue.
```js
		// General element to close the popdown
		// $(document).on('click', '.close-popdown', function(e){
		// 	if($(this).is('a')) {
		// 		e.preventDefault();
		// 	}
		// 	$.fn.close_popdown();
		// });
		
		// // Close the popdown
		// $(document).on('click', '#popdown-opacity', function(e){
		// 	$.fn.close_popdown();			
		// });
```

**Comment by kamaroly** [comment]
@inoyakaigor ,plesde check if the previous commit fixed your issue and close this issue.

**Comment by nicovanzyl** [comment]
This issue should be fixed. @kamaroly thanks for the help, much appreciated! If you have any suggestions please don't hesitate to add a feature request.

**Comment by kamaroly** [comment]
@nicovanzyl ,
Pleasure is mine, I forgot to provided compressed version of previous commit, I hope you managed to do it.I loved this plugin because it's easy and straight forward.

**Comment by nicovanzyl** [comment]
Compressed the file. :)

Glad to hear that, simple is always better.

**Comment by kamaroly** [comment]
:+1:

**Comment by inoyakaigor** [comment]
@kamaroly I've already forgotten what project to use this plugin, but still thank you fix it!
