### ISSUE TITLE
LOVE your plugin

### ISSUE THREAD

**Issue by XanderCam** [Wixel/jquery-popdown#8]
I have one question tho.
If I wanted to trigger your plugin on page load, how would I go about doing that ?

I want to use it as a "first visit" or a "what's new" information box, as well as the intended use.

**Comment by nicovanzyl** [comment]
Hi, XanderCam

a Simple way would be to trigger a click event on the anchor, but that's a bit hacky (here's an example: http://codepen.io/WixelHQ/pen/gMbVRj). I'll make a feature request for the popdown to support different events.
